### ISSUE TITLE
Array vs. 15 named properties?

### ISSUE THREAD

**Issue by shb46** [tachgsfc/tach-avro-schema#74]
https://github.com/nasa-gcn/gcn-schema/blob/fcf288bd8c418c915f291492f452d44e10648be4/gcn/notices/glowbug/alert.example.json#LL24C1-L39C1

Hi,

What was the reason to change the array of 15 with 15 named properties? 

In the current schema the names can be anything? Shouldn't we change that?

Thanks!

**Comment by jracusin** [comment]
We thought it would be easier to read and understand how the array corresponded with the list of detectors as an object.  Please edit the Glowbug schema if we've named the detectors incorrectly.  Although the is in the Glowbug schema, we wanted to write this in a way that it could also be used for GBM, BurstCube, and similar multi-detector scintillator instruments.

**Comment by shb46** [comment]
I'd like to change `additionlProperties` to `properties` and spell all detectors out. Ok?

**Comment by Tohuvavohu** [comment]
Should i list all (constantly changing) operational subfraction of the 32,000 BAT detectors?
What's the scope here?

**Comment by jracusin** [comment]
`additionalProperties` is a special keyword, defining the structure of key value pairs in an object.  However, I've also just realized that we don't need `detector_status` embedded in `properties`.   @dakota002 is going to work on a PR for this.

**Comment by Tohuvavohu** [comment]
>  This detector status is useful to instruments like Glowbug, GBM, BurstCube, etc. 
Can you help me understand how having this info promptly will be used by consumers?

I can certainly see how it would be helpful for later analysis...

**Comment by jracusin** [comment]
> > This detector status is useful to instruments like Glowbug, GBM, BurstCube, etc.
> 
> Can you help me understand how having this info promptly will be used by consumers?
> 
> I can certainly see how it would be helpful for later analysis...

Not necessarily all consumers, but the teams can quickly identify unphysical detector combinations (suggesting a particle trigger).  Boyan was also including info for if the detectors are on or off, because it sounds like some will be off some of the time, so it's useful to distinguish between not triggered (on) and off.  In GCN Classic, GBM includes a 14-digit string with 0's and 1's showing which detectors triggered.  With this detector status object, we're trying to capture all of this information in a more human readable way.
